base/urls.py
"""
chatroom_bot base module URL Configuration
"""
## @package base.urls
#
# Link between views and templates
# @date 19-07-2019
# @version 1.0
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    path('', Home.as_view(), name = "home")
]

chatroom_bot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetCompleteView
)
from users.forms import PasswordConfirmForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('', include('base.urls', namespace="base")),
    path('', include('users.urls')),
    path('user/password/reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='user.passwordreset.confirm.html',
                                        success_url='/user/password/done/',
                                        form_class=PasswordConfirmForm
                                        ),
        name='password_reset_confirm',
    ),
    path(
        'user/password/done/',
        PasswordResetCompleteView.as_view(template_name='user.passwordreset.end.html'),
        name='pass_done',
    ),
]

users/urls.py
"""
chatroom_bot users module URL Configuration
"""
## @package users.urls
#
# Link between views and templates
# @date 19-07-2019
# @version 1.0
from django.urls import path, reverse_lazy
from .views import *
from .forms import PasswordResetForm
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView,
	)

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name = "login"),
    path('logout', LogoutView.as_view(), name = "logout"),
    path('register', RegisterView.as_view(), name = "register"),
    path('account/password/reset/', PasswordResetView.as_view(
    								template_name='user.reset.html',
    								success_url=reverse_lazy('users:reset_done'),
    								form_class=PasswordResetForm),
    	name='forgot'),
    path('accounts/password/done/', PasswordResetDoneView.as_view(
    							   template_name='user.passwordreset.done.html'),
        name='reset_done'),
    path('account/change-pass/', ChangePasswordView.as_view(), name="change_pass"),
]

users/forms.py
"""
chatroom_bot users module formularies
"""
## @package users.forms
#
# Forms of users application
# @date 19-07-2019
# @version 1.0
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
    UserCreationForm
)
from django.forms.fields import (
    CharField, BooleanField
)
from django.forms.widgets import (
    PasswordInput, CheckboxInput
)
from django.contrib.auth.forms import (
    PasswordResetForm, SetPasswordForm, PasswordChangeForm
)
from base.functions import (
    validate_email
)

class LoginForm(forms.Form):
    """!
    Class for login form

    @version 1.0.0
    """
    password = CharField()

    username = CharField()

    remember_me = BooleanField()


    def __init__(self, *args, **kwargs):
        """!
        Metod to override form initial

        @param self <b>{object}</b> Class instance
        @param args <b>{list}</b> Args List
        @param kwargs <b>{dict}</b> Args Dict
        """
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = PasswordInput()
        self.fields['password'].widget.attrs.update({'class': 'validate',
        'placeholder': 'Password'})
        self.fields['username'].widget.attrs.update({'class': 'validate',
        'placeholder': 'Username'})
        self.fields['remember_me'].label = "Remember Me"
        self.fields['remember_me'].widget = CheckboxInput()
        self.fields['remember_me'].required = False

    def clean(self):
        """!
        Method to validate form

        @param self <b>{object}</b> Class instance
        @return Return error on form
        """
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username,password=password)
        if(not user):
            msg = "Invalid user or password"
            self.add_error('username', msg)

    class Meta:
        fields = ('username', 'password', 'remember_me')


class UserRegisterForm(UserCreationForm):
    """!
    Class to register user

    @version 1.0.0
    """
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].required = True
        self.fields['username'].label = 'Username'

        self.fields['password1'].required = True
        self.fields['password1'].label = 'Password'

        self.fields['password2'].required = True
        self.fields['password2'].label = 'Password Repeat'

        self.fields['first_name'].label = 'First Name'

        self.fields['last_name'].label = 'Last Name'

        self.fields['email'].label = 'Email'

    def clean_password_repeat(self):
        """!
        Method to validate passwords

        @param self <b>{object}</b> Class instance
        @return Return field validation
        """
        password = self.cleaned_data['password1']
        password_repeat = self.cleaned_data['password2']
        if(password_repeat!=password):
            raise forms.ValidationError("Password does not match")
        return password_repeat

    def clean_email(self):
        """!
        Method to validate email

        @param self <b>{object}</b> Class instance
        @return Return field with validation
        """
        email = self.cleaned_data['email']
        if(validate_email(email)):
            raise forms.ValidationError("Email exists")
        return email


class PasswordResetForm(PasswordResetForm):
    """!
    Class to reset password

    @version 1.0.0
    """

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control',
                                                  'placeholder': 'Email'})

    def clean(self):
        cleaned_data = super(PasswordResetForm, self).clean()
        email = cleaned_data.get("email")

        if email:
            msg = "Email not found"
            try:
                User.objects.get(email=email)
            except:
                self.add_error('email', msg)



class PasswordConfirmForm(SetPasswordForm):
    """!
    Class to password confirm form

    @version 1.0.0
    """
    def __init__(self, *args, **kwargs):
        super(PasswordConfirmForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'New Password'})
        self.fields['new_password2'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'Repeat Password'})


class PasswordChangeForms(forms.Form):
    """!
    Class for password change

    @version 1.0.0
    """

    old_password = forms.CharField(max_length=20,
        widget=forms.TextInput(attrs={'type':'password'}),
        label="Old Password"
        )

    new_password = forms.CharField(max_length=20,
        widget=forms.TextInput(attrs={'type':'password'}),
        label="New Password"
        )

    new_password_repeat = forms.CharField(max_length=20,
        widget=forms.TextInput(attrs={'type':'password'}),
        label="Repeat New Password"
        )


class PasswordChangeAccount(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeAccount, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'Old Password'})
        self.fields['new_password1'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'New Password'})
        self.fields['new_password2'].widget.attrs.update({'class': 'input-field',
                                                  'placeholder': 'Repeat New Password'})     

users/views.py
"""
chatroom_bot users module views
"""
## @package users.views
#
# Views of users application
# @date 19-07-2019
# @version 1.0
from django.shortcuts import redirect
from django.views.generic import (
    FormView, RedirectView, CreateView, 
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import authenticate, logout, login
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from .forms import (
    LoginForm, UserRegisterForm, PasswordChangeAccount
)
from .constants import SESSION_EXPIRATION


class LoginView(FormView):
    """!
    Class for login form

    @version 1.0.0
    """
    form_class = LoginForm
    template_name = 'user.login.html'
    success_url = reverse_lazy('base:home')

    def form_valid(self, form):
        """!
        Method to validate login form
    
        @param self <b>{object}</b> Class instance
        @param form <b>{object}</b> Form object
        @return Valid Form
        """
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        if self.request.POST.get('remember_me') is not None:
            self.request.session.set_expiry(SESSION_EXPIRATION)
        return super().form_valid(form)
    
    
class LogoutView(RedirectView):
    """!
    Class for logout

    @version 1.0.0
    """
    permanent = False
    query_string = True

    def get_redirect_url(self):
        """!
        Method for redirect
    
        @param self <b>{object}</b> Class instance
        @return Redirect url
        """
        logout(self.request)
        return reverse_lazy('users:login')


class RegisterView(SuccessMessageMixin,CreateView):
    """!
    Class for register user

    @version 1.0.0
    """
    template_name = "user.register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy('base:home')
    success_message = "Successfully registered"
    model = User


class ChangePasswordView(LoginRequiredMixin,FormView):
    """!
    Class for manage change password

    @version 1.0.0
    """
    template_name = "change_password.form.html"
    form_class = PasswordChangeAccount
    success_url = reverse_lazy('base:home')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        """!
        Method for validate data
    
        @param self <b>{object}</b> Class instance
        @param form <b>{object}</b> Form object
        @return Return a redirect
        """
        user = form.save()
        try:
            login(self.request, user)
        except:
            return super().form_valid(form)    
        return super().form_valid(form)

users/templates/change_password.form.html
{% extends 'base.html' %}
{% block title %}Change Password{% endblock %}
{% block content %}
    <div class="content center">
        <form action="" role="form" class="form form-horizontal validate-form change_form" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="center">
                <h3>Change Password</h3><hr>

                {% for field in form %}
                    <div class="col m12 s12">
                        <div class="input-field {% if field.errors %}invalid{% endif %}">
                            <div class="col m4 s4">
                                <div class="row">
                                    {{ field }}
                                    <label for="{{ field.auto_id }}">
                                        {{ field.label }}
                                    </label>
                                </div>
                                {% include 'base.forms.errors.html' with form_errors=field.errors col_title_error='col s2' col_msg_error='col s10' %}
                            </div>
                        </div>
                    </div><br><br><br>
                {% endfor %}

                 <div class="col-md-12 col-sm-12 col-xs-12">
                    <button type="submit" class="btn waves-effect teal">Change</button>
                 </div>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/user.login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="content center">
    <form id="form" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="input-field {% if form.username.errors %}invalid{% endif %}">
            <i class="tiny material-icons prefix">account_circle</i>
            {{ form.username }}
            <label for="icon_prefix {{ form.username.auto_id }}">Username</label>
            {% include 'base.forms.errors.html' with form_errors=form.username.errors col_title_error='col s2' col_msg_error='col s10' %}
        </div>
        
        <div class="input-field {% if form.username.errors %}invalid{% endif %}">
            <i class="tiny material-icons prefix">lock</i>
            {{ form.password }}
            <label for="icon_prefix {{ form.password.auto_id }}">Password</label>
            {% include 'base.forms.errors.html' with form_errors=form.username.errors col_title_error='col s2' col_msg_error='col s10' %}
        </div>
        
        <div class="row">
            <a href="{% url 'users:register' %}" style="cursor: pointer">Register</a> | 
            <a href="{% url 'users:forgot' %}" style="cursor: pointer">Forgot Password?</a>
        </div>
        
        <div class="row">
            <p class="center">
                {{form.remember_me}}
                <label for="id_remember_me">{{form.remember_me.label}}</label>
            </p>
        </div>
        <div>
            <button type="submit" class="btn waves-effect teal">Login</button>
        </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/user.passwordreset.confirm.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Password Recover{% endblock %}
{% block content %}
    <div class="center">
        <h1>Confirm Password</h1><hr>
        <form method="post">
            {% csrf_token %}
            <ul>
                <li class = "text-left"> Your password can not be so similar to your other personal information. </li>
                <li class = "text-left"> Your password must contain at least 8 characters. </li>
                <li class = "text-left"> The password can not be a commonly used password. </li>
                <li class = "text-left"> Your password can not be completely numeric. </li>
            </ul><br>

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="input-field {% if form.new_password1.errors %}invalid{% endif %}">
                    {{ form.new_password1 }}
                    <label for="{{ form.new_password1.auto_id }}">
                        {{ form.new_password1.label }}
                    </label>
                    {% include 'base.forms.errors.html' with form_errors=form.new_password1.errors col_title_error='col s2' col_msg_error='col s10' %}
                </div>
            </div><br><br><br>
          
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="input-field {% if form.new_password2.errors %}invalid{% endif %}">
                    {{ form.new_password2 }}
                    <label for="{{ form.new_password2.auto_id }}">
                        {{ form.new_password2.label }}
                    </label>
                    {% include 'base.forms.errors.html' with form_errors=form.new_password2.errors col_title_error='col s2' col_msg_error='col s10' %}
                </div>
            </div><br><br><br>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <button type="submit" class="btn waves-effect teal">Confirm</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/user.passwordreset.done.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Password Forgot{% endblock %}
{% block content %}
    <div class="center">
        <h1>Info</h1><hr>
        <p>
            The information to retrieve the <b> password </b> was sent to the <b> email </b> provided.
        </p>
    </div>
    <a type="button" class="btn waves-effect teal" href="{% url 'base:home'%}">Back</a>
{% endblock %}

users/templates/user.passwordreset.end.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Password Forgot{% endblock %}
{% block content %}
    <div class="row text-center">
        <h1>Success</h1><hr>
        <p>
          Your password was changed successfully
        </p><br>
    </div>
    <a type="button" class="btn waves-effect teal" href="{% url 'base:home'%}">Back</a>
{% endblock %}

users/templates/user.register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Register{% endblock %}
{% block content %}
  <div class="center">
    <h1>Register</h1><hr>
    <form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
      <div class="col m12 s12">
        <div class="input-field {% if form.username.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.username }}
            <label for="{{ form.username.auto_id }}">
              {{ form.username.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.username.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
      
       <div class="col m12 s12">
        <div class="input-field {% if form.password1.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.password1 }}
            <label for="{{ form.password1.auto_id }}">
              {{ form.password1.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.password1.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
      
      <div class="col m12 s12">
        <div class="input-field {% if form.password2.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.password2 }}
            <label for="{{ form.password2.auto_id }}">
              {{ form.password2.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.password2.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
          
      <div class="col m12 s12">
        <div class="input-field {% if form.first_name.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.first_name }}
            <label for="{{ form.first_name.auto_id }}">
              {{ form.first_name.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.first_name.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
      
      <div class="col m12 s12">
        <div class="input-field {% if form.last_name.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.last_name }}
            <label for="{{ form.last_name.auto_id }}">
              {{ form.last_name.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.last_name.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>
          
      <div class="col m12 s12">
        <div class="input-field {% if form.email.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.email }}
            <label for="{{ form.email.auto_id }}">
              {{ form.email.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.email.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>

      <div class="col m12 s12">
         <a type="button" class="btn waves-effect teal" href="{% url 'base:home' %}">Back</a>
         <button type="submit" class="btn waves-effect teal">Register</button>
      </div>
    </form>
  </div>
  <br />
{% endblock %}

{% block extraJs %}
<script type="text/javascript">
  $('.datepicker').pickadate({
    selectMonths: true,
    selectYears: 15,
    format: 'dd/mm/yyyy'
  });
</script>
{%endblock%}

users/templates/user.reset.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Password Forgot{% endblock %}
{% block content %}
    <div class="center">
        <h1>Password Forgot</h1><hr>
        <form method="post">
            {% csrf_token %}
            <div class="col m12 s12">
                <div class="input-field {% if form.email.errors %}invalid{% endif %}">
                    {{ form.email }}
                    <label for="{{ form.email.auto_id }}">
                        {{ form.email.label }}
                    </label>
                    {% include 'base.forms.errors.html' with form_errors=form.email.errors col_title_error='col s2' col_msg_error='col s10' %}
                    <div class="col s1"><i class="ion ion-ios-medical"></i></div>
                </div>
            </div><br><br><br>
            <div class="col m12 s12">
                <button type="submit" class="btn waves-effect teal">Send</button>
            </div>
        </form>
    </div>

{% endblock %}