base/urls.py
"""
chatroom_bot base module URL Configuration
"""
## @package base.urls
#
# Link between views and templates
# @date 19-07-2019
# @version 1.0
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    path('', Home.as_view(), name = "home")
]

chat/urls.py
"""
chatroom_bot chat module URL Configuration
"""
## @package chat.urls
#
# Link between views and templates
# @date 19-07-2019
# @version 1.0
from django.urls import path
from .views import *

app_name = 'chat'
urlpatterns = [
    path('', RoomView.as_view(), name = "chat_list"),
    path('create-room',CreateRoomView.as_view(), name = "room_create"),
    path('<int:room>', ChatView.as_view(), name = "chat"),
    path('list-comment', ListComment.as_view(), name="list_comment"),
    path('comment', AddComment.as_view(), name="comment"),
]

chatroom_bot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetCompleteView
)
from users.forms import PasswordConfirmForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('', include('base.urls', namespace="base")),
    path('', include('users.urls')),
    path('user/password/reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='user.passwordreset.confirm.html',
                                        success_url='/user/password/done/',
                                        form_class=PasswordConfirmForm
                                        ),
        name='password_reset_confirm',
    ),
    path(
        'user/password/done/',
        PasswordResetCompleteView.as_view(template_name='user.passwordreset.end.html'),
        name='pass_done',
    ),
]

users/urls.py
"""
chatroom_bot users module URL Configuration
"""
## @package users.urls
#
# Link between views and templates
# @date 19-07-2019
# @version 1.0
from django.urls import path, reverse_lazy
from .views import *
from .forms import PasswordResetForm
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView,
	)

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name = "login"),
    path('logout', LogoutView.as_view(), name = "logout"),
    path('register', RegisterView.as_view(), name = "register"),
    path('account/password/reset/', PasswordResetView.as_view(
    								template_name='user.reset.html',
    								success_url=reverse_lazy('users:reset_done'),
    								form_class=PasswordResetForm),
    	name='forgot'),
    path('accounts/password/done/', PasswordResetDoneView.as_view(
    							   template_name='user.passwordreset.done.html'),
        name='reset_done'),
    path('account/change-pass/', ChangePasswordView.as_view(), name="change_pass"),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
"""
chatroom_bot base module views
"""
## @package base.views
#
# Views of base application
# @date 19-07-2019
# @version 1.0
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

    
class Home(LoginRequiredMixin,TemplateView):
    """!
    Initial class

    @version 1.0.0
    """
    template_name = "home.html"

base/templates/base.footer.html
<footer class="page-footer teal">
    <div class="">
        <div class="center">
            <p>
                <span id="year-info-develop">{% now "Y" %}</span>
            </p>
        </div>
    </div>
</footer>

base/templates/base.forms.errors.html
{% if form_errors %}
    <div class="error-notice">
        <div class="oaerror danger">
            <div class="row">
                <div class="{% if not col_title_error %}col s3{% else %}{{ col_title_error }}{% endif %}">
                    <strong>Error</strong>
                </div>
                <div class="{% if not col_msg_error %}col s9{% else %}{{ col_msg_error }}{% endif %}">
                    {% if custom_message_error %}{{ custom_message_error }}{% else %}{{ form_errors }}{% endif %}
                </div>
            </div>

        </div>
    </div>
{% endif %}

base/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <title>{% block title %}Chat Room Bot{% endblock %}</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">

        <link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'materialize/material_icon/icon.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
        
        <script src="{% static 'jquery/jquery-3.1.0.min.js' %}"></script>
        <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
        <script src="{% static 'js/functions.js' %}"></script>
        {% block headScript %}{%endblock%}
    </head>
    <body class="grey lighten-4">
        {% include 'base.nav.bar.html' %}
        <main>
        {% block superContent%}
            <div class="container">
                <div class="card-panel">
                    {% block content %}{% endblock %}
                </div>
            </div>
        {% endblock %}
        </main>
        {% block modals %}{% endblock %}
        {% include 'base.footer.html' %}
    </body>
    {% block extraJs %}{%endblock%}
    {% include 'base.vars.javascript.html' %}
</html>

base/templates/base.nav.bar.html
<nav class="teal">
  <div class="nav-wrapper">
    <a class="brand-logo" href="{% url 'base:home' %}">Chat Room Bot</a>
    {% if request.user.is_authenticated %}
    <a href="#" data-activates="slide-out" class="button-collapse white-text"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="#!" class="dropdown-button" data-activates="dropdown1" data-beloworigin="true">Welcome <b>{{request.user.username}}</b> <i class="material-icons right">arrow_drop_down</i></a></li>
      <ul id='dropdown1' class='dropdown-content' data-belloworigin="true">
        <li><a href="{% url 'chat:chat_list' %}">Chat</a></li>
        <li><a href="{% url 'users:change_pass' %}">Change Password</a></li>
        <li><a href="{% url 'users:logout' %}">Logout</a></li>
      </ul>
    </ul>
    {% else %}
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#">Welcome <b>Anonymous</b></a></li>
      </ul>
    {% endif %}
  </div>
</nav>

base/templates/base.paginator.html
<ul class="pagination center">
    {% if paginator.has_previous %}
        <li>
            <span>
                <a href="?page={{ paginator.previous_page_number }}" class="waves-effect">
                    <i class="material-icons tiny" id="tiny">chevron_left</i> Prev
                </a>
            </span>
        </li>
    {% endif %}
        <li>
            <span>Page {{ paginator.number }} of {{ paginator.paginator.num_pages }}.</span>
        </li>
    {% if paginator.has_next %}
        <li>
            <span>
                <a href="?page={{ paginator.next_page_number }}" class="waves-effect">
                    Next <i class="material-icons" id="tiny">chevron_right</i>
                </a>
            </span>
        </li>
    {% endif %}
</ul>

base/templates/base.vars.javascript.html
<script type="text/javascript">

  // URL for list comment
  const URL_LIST_COMMENT = "{% url 'chat:list_comment' %}"

  // URL for create comment
  const URL_CREATE_COMMENT = "{% url 'chat:comment' %}"
    
</script>
    

base/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="center">
        <p>Welcome to realtime <b> Chatroom </b></p>
    </div>
{% endblock %}