base/urls.py
"""
chatroom_bot base module URL Configuration
"""
## @package base.urls
#
# Link between views and templates
# @date 19-07-2019
# @version 1.0
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    path('', Home.as_view(), name = "home")
]

chat/urls.py
"""
chatroom_bot chat module URL Configuration
"""
## @package chat.urls
#
# Link between views and templates
# @date 19-07-2019
# @version 1.0
from django.urls import path
from .views import *

app_name = 'chat'
urlpatterns = [
    path('', RoomView.as_view(), name = "chat_list"),
    path('create-room',CreateRoomView.as_view(), name = "room_create"),
    path('<int:room>', ChatView.as_view(), name = "chat"),
    path('list-comment', ListComment.as_view(), name="list_comment"),
    path('comment', AddComment.as_view(), name="comment"),
]

chatroom_bot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetCompleteView
)
from users.forms import PasswordConfirmForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('', include('base.urls', namespace="base")),
    path('', include('users.urls')),
    path('user/password/reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='user.passwordreset.confirm.html',
                                        success_url='/user/password/done/',
                                        form_class=PasswordConfirmForm
                                        ),
        name='password_reset_confirm',
    ),
    path(
        'user/password/done/',
        PasswordResetCompleteView.as_view(template_name='user.passwordreset.end.html'),
        name='pass_done',
    ),
]

chat/models.py
"""
chatroom_bot chat module models
"""
## @package chat.models
#
# Models of chat application
# @date 19-07-2019
# @version 1.0
from django.contrib.auth.models import User
from django.db import models

class ChatRoom(models.Model):
    """!
    Class for chat room model

    @copyright MIT
    @version 1.0.0
    """
    name = models.CharField(max_length=50)

    def __str__(self):
        """!
        Function to show string

        @return Return chat string
        """
        return self.name

class RoomUsers(models.Model):
    """!
    Class for chat room users

    @copyright MIT
    @version 1.0.0
    """
    user = models.ForeignKey(User, related_name='user_room', on_delete=models.CASCADE)

    room = models.ForeignKey(ChatRoom, related_name='room_room', on_delete=models.CASCADE)

    def __str__(self):
        """!
        Function to show string

        @return Return chat string
        """
        return self.room.name


class Comment(models.Model):
    """!
    Class for comment model

    @copyright MIT
    @version 1.0.0
    """
    fk_user_emit = models.ForeignKey(User, related_name='user_emit', on_delete=models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    visible = models.BooleanField(default=True)
    seen = models.BooleanField(default=False)
    room = models.ForeignKey(ChatRoom, related_name='chat_room', on_delete=models.CASCADE)

    class Meta:
        """!
            Class for model metadata
        """
        ordering = ('date',)
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        """!
        Function to show string

        @return Return comment string
        """
        return self.comment

chat/forms.py
"""
chatroom_bot chat module formularies
"""
## @package chat.forms
#
# Forms of chat application
# @date 19-07-2019
# @version 1.0
from django import forms
from .models import ChatRoom

class ChatSendForm(forms.Form):
  """!
  Class for chat send form

  @version 1.0.0
  """ 

  comment = forms.CharField()


class ChatRegisterForm(forms.ModelForm):
  """!
  Class for chat room form

  @version 1.0.0
  """ 
  class Meta:
    model = ChatRoom
    fields = '__all__'

chat/views.py
"""
chatroom_bot chat module views
"""
## @package chat.views
#
# Views of chat application
# @date 19-07-2019
# @version 1.0
from django.core import serializers
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, ListView, CreateView

from .forms import ChatSendForm, ChatRegisterForm
from .models import Comment, ChatRoom, RoomUsers
from .tasks import get_stock_quote
from .constants import COMMAND_STOCK


class RoomView(LoginRequiredMixin, ListView):
    """!
    Class for see rooms

    @version 1.0.0
    """
    model = ChatRoom
    template_name = "room.list.html"
    paginate_by = 10

class CreateRoomView(LoginRequiredMixin, CreateView):
    """!
    Class for create rooms

    @version 1.0.0
    """
    model = ChatRoom
    template_name = "room.register.html"
    form_class = ChatRegisterForm
    success_url = reverse_lazy('chat:chat_list')


class ChatView(LoginRequiredMixin, FormView):
    """!
    Class to see chats

    @version 1.0.0
    """
    template_name = "chat.html"
    form_class = ChatSendForm

    def dispatch(self, *args, **kwargs):
        """!
        Method to dispatch view

        @param self <b>{object}</b> Class instance
        @param args <b>{object}</b> Args list
        @param kwargs <b>{object}</b> Args dict
        @return Context data
        """
        room_id = self.kwargs.get('room')
        room = ChatRoom.objects.filter(pk=room_id)

        if not room:
            return redirect('chat:chat_list')

        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        """!
        Method to manage context data on view

        @param self <b>{object}</b> Class instance
        @param kwargs <b>{object}</b> Args dict
        @return Context data
        """
        room_id = self.kwargs['room']
        RoomUsers.objects.update_or_create(user=self.request.user,room_id=room_id,
            defaults={'user': self.request.user,'room_id': room_id },)
        kwargs['users'] = RoomUsers.objects.filter(room_id=room_id).all()
        kwargs['room_id'] = room_id
        return super().get_context_data(**kwargs)

class ListComment(View):
    """!
    Class to list comments

    @version 1.0.0
    """
    def get(self, request, **kwargs):
        room_id = request.GET.get('room_id')
        serialized_object = None
        if room_id is not None:
            comments = Comment.objects.filter(room_id=room_id).order_by('-date')[:50]
            comments = reversed(comments)
            serialized_object = serializers.serialize('json', comments)

        return JsonResponse(serialized_object, safe=False)

@method_decorator(csrf_exempt, name='dispatch')
class AddComment(View):
    """!
    Class to add comment

    @version 1.0.0
    """
    def post(self, request, **kwargs):
        comment = request.POST.get('comment')
        user_emit = request.POST.get('user_emit')
        room_id = request.POST.get('room_id')

        try:
            user_emit = User.objects.get(pk=user_emit)
        except Exception as e:
            print(e)
            user_emit = None
        serialized_object = None
        if user_emit is not None and room_id is not None:
            command_stock = COMMAND_STOCK
            if comment.startswith(command_stock): # and len(comment) > len(command_stock):
                get_stock_quote.apply_async((comment[len(command_stock):], user_emit.pk, room_id))
            else:
                try:
                    comment_obj = Comment()
                    comment_obj.fk_user_emit = user_emit
                    comment_obj.comment = comment
                    comment_obj.room_id = room_id
                    comment_obj.save()
                    serialized_object = serializers.serialize('json', [comment_obj])
                except Exception as e:
                    print(e)
                    serialized_object = {'error': 'Fail to send message'}

        return JsonResponse(serialized_object, safe=False)

chat/templates/chat.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Chat{% endblock %}
{% block content %}
    <div class="row">
      <div class="col m2">
        <div class="row center">Users</div><hr/>
        {% for user in users %}
          <div class="row">
            <a href="#">
              {{user.user.username}}
            </a>
          </div>
        {% endfor %}
      </div>
      <div class="col m10">
        <div class="row center">Chat</div><hr/>
        <div class="chat-log">
        </div>
        <div class="chat-box">
          <div class="col m10">
            <div class="input-field {% if form.comment.errors %}invalid{% endif %}">
                  {{ form.comment }}
                  <label for="icon_prefix {{ form.comment.auto_id }}">Message</label>
                  {% include 'base.forms.errors.html' with form_errors=form.comment.errors col_title_error='col s2' col_msg_error='col s10' %}
              </div>
          </div>
          <div class="col m2">
            <button class="btn-floating btn-large" id="send" onclick="testMsg()">
              <i class="tiny material-icons prefix">send</i>
            </button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}
{% block extraJs %}
<script>
  const room_id = "{{ room_id }}";
  var chatSocket = new WebSocket(
    'ws://' + window.location.host +
    '/chat/' + room_id);

  chatSocket.onmessage = function(e) {
    var data = JSON.parse(e.data);

    var send = data.seen ? 'done_all' :'done';
    if(data.fk_user_emit=="{{user.id}}")
    {
      var position = "sended right";
      send = 'done_all';
    }
    else{
      var position = "recived left";
    }
    var html = '<div class="row">';
    html += '<div class="'+position+'">'+data.comment;
    html += '<br/><i class="tiny material-icons prefix">'+send+'</i> | ';
    html += '<small>'+ data.fk_user_emit +'</small> |';
    html += '<small>'+ data.date +'</small></div>';
    html += '</div>';
    $('.chat-log').append(html);
    //$('.chat-log').scrollTop($('.chat-log').scrollTop()+100)
  };

  chatSocket.onopen = function(e) {
    console.info('Chat socket conected');
  };

  chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
  };

  function testMsg(){
    var token = $('input').val()
    var comment = $('#id_comment').val();
    if (comment!=''){
      sendMessage('{{user.id}}',comment,room_id)
      $('#id_comment').val('')
    }
  }
  document.querySelector('#id_comment').onkeyup = function(e) {
    if (e.keyCode === 13) {
      document.querySelector('#send').click();
    }
  };

  $(document).ready(function(){
    get_comment(room_id,'{{user.id}}');
  });
</script>
{%endblock%}

chat/templates/room.list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Chat Rooms{% endblock %}
{% block content %}
  <a 
    class="btn-floating btn-large waves-effect waves-light teal right"
    href="{% url 'chat:room_create' %}"
  >
    <i class="material-icons">add</i>
  </a>
  <h1>Chat Rooms</h1> 
  <div class="row">
  {% for chat_room in object_list %}
    <div class="col m6">
      <div class="card">
        <div class="card-content">
            <span class="card-title"><b>Chat Room Name: </b>{{ chat_room.name }}</span>
        </div>
        <div class="card-action">
            <a type="button" class="btn waves-effect teal" href="{% url 'chat:chat' chat_room.pk %}">
              <i class="material-icons left">arrow_forward_ios</i> Enter
            </a>
        </div>
      </div>
    </div>
  {% empty %}
      <h4>No chat room created.</h4>
  {% endfor %}
  </div>
  {% include 'base.paginator.html' with paginator=page_obj %}
{% endblock %}

chat/templates/room.register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Add Room{% endblock %}
{% block content %}
  <div class="center">
    <h1>Add Room</h1><hr>
    <form action="{% url 'chat:room_create' %}" method="post">
    {% csrf_token %}
      <div class="col m12 s12">
        <div class="input-field {% if form.name.errors %}invalid{% endif %}">
          <div class="col m4 s4">
            {{ form.name }}
            <label for="{{ form.name.auto_id }}">
              {{ form.name.label }}
            </label>
            {% include 'base.forms.errors.html' with form_errors=form.name.errors col_title_error='col s2' col_msg_error='col s10' %}
          </div>
          
        </div>
      </div><br><br><br>

      <div class="col m12 s12">
        <a type="button" class="btn waves-effect teal" href="{% url 'base:home' %}">Back</a>
        <button type="submit" class="btn waves-effect teal">Register</button>
      </div>
    </form>
  </div>
{% endblock %}